### PR TITLE
FIX README badges

### PR DESCRIPTION
**Pull request by patoroco**

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by patoroco** [comment]
I signed it!

**Comment by snowplowcla** [comment]
Sorry, I don't see a signature.

**Comment by alexanderdean** [comment]
Hey @patoroco - we can't find your signature in either of our CLA response tables. Can you try and resubmit?

**Pull request closed without merging**
